name: Build SFI

on:
  workflow_dispatch:
    inputs:
      sing-box_version:
        description: 'sing-box version'
        required: true
      target_env:
        description: 'target env'
        required: true
        type: environment

jobs:
  build:
    name: Build v${{ github.event.inputs.sing-box_version }} for ${{ github.event.inputs.target_env }}
    runs-on: macos-latest
    environment: 
      name: ${{ github.event.inputs.target_env }}
    env:
      VERSION: ${{ github.event.inputs.sing-box_version }}
      GH_ENV: ${{ github.event.inputs.target_env }}

    steps:
      - name: Checkout SFA (Apple)
        uses: actions/checkout@v5
        with:
          path: sing-box-for-apple

      - name: Checkout sing-box
        uses: actions/checkout@v5
        with:
          repository: SagerNet/sing-box
          ref: v${{ github.event.inputs.sing-box_version }}
          path: sing-box

      - name: Setup Go Environment
        uses: actions/setup-go@v6
        with:
          go-version-file: sing-box/go.mod

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Tweak Project Before Build
        env:
          PACKAGE_NAME: ${{ secrets.PACKAGE_NAME }}
          GROUP_NAME: ${{ secrets.GROUP_NAME }}

        working-directory: ./sing-box-for-apple
        run: |
          agvtool new-marketing-version ${VERSION}

          if [ -n "${PACKAGE_NAME}" ]; then
            find . \( -name "*.swift" -o -name "*.plist" -o -name "*.pbxproj" \)  -type f -exec perl -i -pe "s/io\.nekohasekai\.sfavt/${PACKAGE_NAME}/g" {} +
          else
            echo "Package Name not provided, skipping update."
          fi

          if [ -z "${GROUP_NAME}" ]; then
            echo "Error: GROUP_NAME secret is not set."
            exit 1
          fi

          perl -i -pe "s/groupName\\s*=.*/groupName = \"${GROUP_NAME}\"/" Library/Shared/FilePath.swift

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('sing-box/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Initialize Libbox Build Environment
        run: make lib_install
        working-directory: ./sing-box

      - name: Build Libbox
        run: make lib_ios
        working-directory: ./sing-box

      - name: Get Xcode DerivedData path
        id: xcode-deriveddata-path
        working-directory: ./sing-box-for-apple
        run: echo "path=$(xcodebuild -project sing-box.xcodeproj -scheme SFI -showBuildSettings | grep -m 1 "BUILD_DIR" | grep -oEi "\/.*" | sed 's|/Build/Products||')/SourcePackages" >> $GITHUB_OUTPUT

      - name: Cache Xcode (SPM) dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.xcode-deriveddata-path.outputs.path }}
          key: ${{ runner.os }}-xcode-spm-${{ hashFiles('sing-box-for-apple/sing-box.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-xcode-spm-

      - name: Build Archive
        working-directory: ./sing-box-for-apple
        run: |
          xcodebuild clean -scheme SFI && \
          xcodebuild archive -scheme SFI \
                         -configuration Release \
                         -destination 'generic/platform=iOS' \
                         -archivePath build/SFI.xcarchive \
                         CODE_SIGN_IDENTITY="" \
                         CODE_SIGNING_REQUIRED=NO

      - name: Package IPA
        run: |
          mkdir Payload
          cp -r sing-box-for-apple/build/SFI.xcarchive/Products/Applications/sing-box.app Payload/ && \
          zip -q -r SFI-v${VERSION}-${GH_ENV}.ipa Payload

      - name: Encrypt IPA
        env:
          ARTIFACT_PASSWORD: ${{ secrets.ARTIFACT_PASSWORD }}
        run: |
          if [ -z "${ARTIFACT_PASSWORD}" ]; then
            echo "Error: ARTIFACT_PASSWORD secret is not set."
            exit 1
          fi
          zip -q -9 -P "${ARTIFACT_PASSWORD}" SFI-v${VERSION}-${GH_ENV}.zip SFI-v${VERSION}-${GH_ENV}.ipa

      - name: Upload Encrypted Artifact
        uses: actions/upload-artifact@v4
        with:
          name: IPA-v${{ github.event.inputs.sing-box_version }}-${{ github.event.inputs.target_env }}
          path: SFI-v${{ github.event.inputs.sing-box_version }}-${{ github.event.inputs.target_env }}.zip